# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'hw9' do
  pod 'Alamofire', '~> 4.7'
  pod 'Alamofire-SwiftyJSON'
  pod 'EasyToast'
  pod 'SwiftSpinner'
  pod 'McPicker'
  pod 'Cosmos'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
end
